{
 "title": "Royal Caribbean",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Year", "query": { "query": "label_values(datelabel)" } },
   { "name": "Month", "query": { "query": "label_values(datelabel)" } },
   { "name": "Ship", "query": { "query": "label_values(ship)" } },
   { "name": "DeparturePort", "query": { "query": "label_values(departureport)" } },
   { "name": "CruiseDays", "query": { "query": "label_values(days)" } },
   { "name": "CabinClass", "query": { "query": "label_values(stateroomclass)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cruise Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Interior",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"INTERIOR\"}",
     "legendFormat": "{{ship}} in {{stateroomclass}} from {{departureport}} on {{datelabel}} for {{days}} days"
    }
   ]
  },
  {
   "title": "Ocean View",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"OUTSIDE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balcony",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"BALCONY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suite",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"DELUXE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Averages by Ship and Cabin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Price by Ship",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (ship) (royal_external_price{departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\"})",
     "legendFormat": "{{ship}}"
    }
   ]
  },
  {
   "title": "Average Price by Cabin Class",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (stateroomclass) (royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\"})",
     "legendFormat": "{{stateroomclass}}"
    }
   ]
  },
  { "title": "HTTP Request Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Request Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "royal_external_url_connect_time_ms",
     "legendFormat": "Connect Time {{ url }}"
    },
    { "expr": "royal_external_url_dns_ms", "legendFormat": "DNS Lookup {{ url }}" },
    {
     "expr": "royal_external_url_first_byte_ms",
     "legendFormat": "First Byte {{ url }}"
    },
    { "expr": "royal_external_url_response_ms", "legendFormat": "Connect Time {{ url }}" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{job=\"royalcaribbean-prometheus-exporter\"}[5m])",
     "legendFormat": "allocated"
    }
   ]
  }
 ]
}